version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs: 
  build: 
    docker:       
      - image: circleci/node:12.13.1    
    working_directory: ~/repo
    steps:      
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm i gh-pages
      - run: git config --global user.email "slimani.ibr@gmail.com"
      - run: git config --global user.name "Slimani-Ibrahim"
      - run: npm run deploy