version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs: 
  build: 
    docker:       
      - image: buildpack-deps:trusty        
    steps:       
      - run: npm cache clean --force
      - run: npm install
      - run: npm run build          
