version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs: 
  build: 
    docker:       
      - image: circleci/node:12.14.1     
    steps:       
      - run: npm install
      - run: npm run build          
