version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs: 
  build: 
    docker:       
      - image: circleci/node:12.13.1    
    working_directory: ~/repo
    steps:      
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm i gh-pages
      - run:
          name: git conf
          command: |
            git config --global user.email "slimani.ibr@gmail.com"
            git config --global user.name "Slimani-Ibrahim"
      - add_ssh_keys:
          fingerprints:
            - "02:21:37:25:65:ca:42:b5:ba:77:fb:9e:9d:36:d4:b5"
      - run: npm run deploy